class MatchModel {
  late String date;
  late String teamA;
  late String teamB;
  late int teamAScore;
  late double odds1xbet;
  late double oddsBetsafe;
  late double oddsBetsson;
  late int likesCount;
  late int starsCount;
  late int viewsCount;
  late int sharesCount;
  late String channels;
  late String stadium;
  late String referee;
  late String refereeAvatar;
  late String refereeStats;
  late String teamAImage;
  late String teamBImage;
  late double redCardMedia;
  late double yellowCardMedia;
  late String teamAStats;
  late String teamBStats;
  late String id;

  MatchModel.fromJson(Map<String, dynamic> json) {
    date = json['date'];
    teamA = json['team_a'];
    teamB = json['team_b'];
    teamAScore = json['team_a_score'];
    odds1xbet = json['1xbet_odds_avg'];
    oddsBetsafe = json['betsafe_odds_avg'];
    oddsBetsson = json['betsson_odds_avg'];
    likesCount = json['likes_count'];
    starsCount = json['stars_count'];
    viewsCount = json['views_count'];
    sharesCount = json['shares_count'];
    channels = json['channels'];
    stadium = json['stadium'];
    referee = json['referee'];
    refereeAvatar = json['referee_avatar'];
    refereeStats = json['referee_stats'];
    teamAImage = json['team_a_image'];
    teamBImage = json['team_b_image'];
    redCardMedia = json['red_card_media'];
    yellowCardMedia = json['yellow_card_media'];
    teamAStats = json['team_a_stats'];
    teamBStats = json['team_b_stats'];
    id = json['id'];
  }
}
